module.exports = {
	adaptiveBri: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Adaptive Brightness",
				de: "Adaptive Helligkeit",
				ru: "Адаптивная яркость",
				pt: "Brilho adaptativo",
				nl: "Adapiteer Brightness",
				fr: "Luminosité adaptative",
				it: "Luminosità adattiva",
				es: "Adaptive Brightness",
				pl: "Brightness adaptacyjny",
				uk: "Адаптивна яскравість",
				"zh-cn": "修 道",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	adaptiveCt: {
		type: "channel",
		common: {
			name: "adaptiveCt",
		},
		native: {},
	},
	"adaptiveCt.adaptiveCtMode": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Mode for Adaptive Colortemperature",
				de: "Modus für adaptive Farbtemperatur",
				ru: "Режим для адаптации Colortemperature",
				pt: "Modo de temperatura adaptativa da cor",
				nl: "Mode voor Adaptieve Colortemperatuur",
				fr: "Mode pour la couleur adaptative",
				it: "Modalità per colori adattivi",
				es: "Mode for Adaptive Colortemperature",
				pl: "Przewodnik adaptacyjny",
				uk: "Режим адаптивної кольорової температури",
				"zh-cn": "A. 资格认证",
			},
			type: "string",
			role: "switch.mode",
			def: "solar",
			states: {
				linear: "Linear",
				solar: "Solar",
				solarInterpolated: "Solar Interpolated",
				timedInterpolated: "StartYourDay Interpolated",
				timed: "StartYourDay",
			},
		},
		native: {},
	},
	"adaptiveCt.adaptiveCtTime": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Start time adaptive colortemperature with mode: StartYourDay",
				de: "Startzeit adaptive Farbtemperatur mit Modus: StartYourDay",
				ru: "Начните время адаптивной colortemperature с режимом: StartYourDay",
				pt: "Tempo de início adaptativo colortemperatura com modo: StartYourDay",
				nl: "Begin met tijd aanpassen aan kleurtemperatuur met mode: StartYourDay",
				fr: "Démarrez la température de couleur adaptative avec le mode: StartYourDay",
				it: "Avviare la temperatura di colore adattativa di tempo con la modalità: StartYourDay",
				es: "Comience la temperatura de color adaptable con modo: StartYourDay",
				pl: "Od czasu adaptacyjnego do temperatury w trybie: Start StartYourDay",
				uk: "Час початку адаптивного кольорутемператури з режимом: StartYourDay",
				"zh-cn": "1. 采用模式调整成色: 导 言 日 日",
			},
			type: "string",
			unit: "Uhr",
			role: "value",
			def: "06:00",
		},
		native: {},
	},
	"adaptiveCt.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Adaptive Colortemperature enabled?",
				de: "Adaptive Farbtemperatur aktiviert?",
				ru: "Адаптивный Colortemperature",
				pt: "Temperatura de cor adaptativa",
				nl: "Vertaling:",
				fr: "Température de couleur adaptative",
				it: "Colortemperatura adattiva",
				es: "Temperatura de color adaptativa",
				pl: "Colortemperatura adaptacyjna",
				uk: "Адаптивна колірна температура",
				"zh-cn": "资格",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	autoOffLux: {
		type: "channel",
		common: {
			name: "autoOffLux",
		},
		native: {},
	},
	"autoOffLux.dailyLock": {
		type: "state",
		common: {
			read: true,
			write: false,
			name: {
				en: "Switch lock",
				de: "Schaltsperre",
				ru: "Переключить замок",
				pt: "Bloqueio de interruptor",
				nl: "Vertaling:",
				fr: "Verrouillage",
				it: "Interruttore di blocco",
				es: "Cierre de interruptor",
				pl: "Switch",
				uk: "Блокування перемикача",
				"zh-cn": "黑暗锁",
			},
			type: "boolean",
			role: "indicator",
			def: false,
		},
		native: {},
	},
	"autoOffLux.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness controlled auto off enabled?",
				de: "Helligkeitabhängiges auto-aus aktiviert?",
				ru: "Яркость управляемая авто отключена?",
				pt: "Brilho controlado auto desligado activado?",
				nl: "Brightness gecontroleerde auto van gehandicapten?",
				fr: "Auto-arrêt contrôlé de luminosité activé ?",
				it: "Attivazione automatica controllata luminosità?",
				es: "¿Un auto controlado por Brightness?",
				pl: "Brightness sterował autom?",
				uk: "Яскравість керована автоматично вимкнено?",
				"zh-cn": "控制汽车的自由?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"autoOffLux.minLux": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness for auto off",
				de: "Helligkeit für Auto-aus",
				ru: "Яркость для автовыхода",
				pt: "Brilho para auto off",
				nl: "Brightness for auto off",
				fr: "Brightness for auto off",
				it: "Luminosità per auto off",
				es: "Brillo para auto apagado",
				pl: "Brightness for auto off",
				uk: "Яскравість для автоматичного вимкнення",
				"zh-cn": "汽车的可靠性",
			},
			type: "number",
			role: "level.brightness",
			def: 500,
			min: 0,
			unit: "lux",
		},
		native: {},
	},
	"autoOffLux.operator": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Should auto off happen if brightness more or less minLux",
				de: "Auto-aus wenn Helligkeit mehr oder weniger minLux",
				ru: "Должен ли автоматизироваться, если яркость больше или меньше minLux",
				pt: "Deve acontecer automaticamente se o brilho mais ou menos minLux",
				nl: "Er zou auto's moeten plaatsvinden als helderheid of minder",
				fr: "Si la luminosité est plus ou moins minLux",
				it: "Dovrebbe auto spento accadere se la luminosità più o meno minLux",
				es: "Si el auto apagado sucede si el brillo más o menos minLux",
				pl: "Auto zdejmuje się, jeśli jasność jest mniejsza niż minLux",
				uk: "Якщо яскравість більше або менше minLux",
				"zh-cn": "如果光明更小或小微不足道的光知会发生尸体解剖",
			},
			type: "string",
			role: "state",
			def: ">",
			states: {
				">": ">",
				"<": "<",
			},
		},
		native: {},
	},
	autoOffTimed: {
		type: "channel",
		common: {
			name: "autoOffTimed",
		},
		native: {},
	},
	"autoOffTimed.autoOffTime": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Time until auto off",
				de: "Zeit bis Auto-aus",
				ru: "Время до авто",
				pt: "Tempo até auto off",
				nl: "Tijd tot auto",
				fr: "Temps écoulé jusqu ' à ce qu ' il s ' échappe",
				it: "Tempo fino al decollo automatico",
				es: "Tiempo hasta el auto apagado",
				pl: "Czas do czasu aż do odwołania samochodu",
				uk: "Час до автоматичного вимкнення",
				"zh-cn": "时间直到尸体解剖",
			},
			type: "number",
			role: "level.timer",
			def: 120,
			min: 0,
			unit: "s",
		},
		native: {},
	},
	"autoOffTimed.countdown": {
		type: "state",
		common: {
			read: true,
			write: false,
			name: {
				en: "Countdown to auto off",
				de: "Countdown zum auto off",
				ru: "Обратный отсчет к авто",
				pt: "Contagem regressiva para auto off",
				nl: "Vertaling:",
				fr: "Compte à rebours pour décoller",
				it: "Conto alla rovescia per disattivare",
				es: "Cuenta atrás para auto apagado",
				pl: "Countdown, aby odejść z samochodu",
				uk: "Відхилення від авто",
				"zh-cn": "解剖",
			},
			type: "number",
			role: "value",
			def: 0,
			min: 0,
			unit: "s",
		},
		native: {},
	},
	"autoOffTimed.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Timecontrolled auto off enabled?",
				de: "Zeitgesteuertes Auto-aus?",
				ru: "Timecontrolled auto off включен?",
				pt: "Desligado automático com tempo activado?",
				nl: "Beheerste auto van gehandicapten?",
				fr: "Désactiver l'autocommande ?",
				it: "Attivazione automatica controllata dal tempo?",
				es: "Autocontrolado a tiempo activado?",
				pl: "Autostrada czasu została zwolniona?",
				uk: "Увімкнути автоматичне вимкнення часу?",
				"zh-cn": "时间控制的汽车?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"autoOffTimed.noAutoOffWhenMotion": {
		type: "state",
		common: {
			type: "boolean",
			read: true,
			write: true,
			name: {
				en: "No timed auto off if new motion detected",
				de: "Kein zeitgesteuertes Auto aus, wenn neue Bewegung erkannt wird",
				ru: "Нет времени авто, если новое движение обнаружено",
				pt: "Não há auto desligado se novo movimento detectado",
				nl: "Geen auto uitgeschakeld als er een nieuwe beweging is",
				fr: "Pas de décalage automatique si le nouveau mouvement est détecté",
				it: "Non c'è auto timer fuori se il nuovo movimento rilevato",
				es: "Sin tiempo de apagado si se detecta nuevo movimiento",
				pl: "Bez czasu, jeśli nowy ruch nie wykrył się z ruchu",
				uk: "У разі виявлення нового руху",
				"zh-cn": "如果发现的新动议,任何时间的汽车",
			},
			role: "switch",
			def: true,
		},
		native: {},
	},
	"autoOffTimed.noticeBri": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness for notice before auto off",
				de: "Helligkeit für Hinweis bevor Auto-aus",
				ru: "Яркость для уведомления перед автовыходом",
				pt: "Brilho para aviso antes de auto off",
				nl: "Brightness voor de auto",
				fr: "Luminosité avant l'auto-arrêt",
				it: "Luminosità per avviso prima di spegnere auto",
				es: "Brillo para aviso antes de apagar el auto",
				pl: "Bright for notice before auto off",
				uk: "Яскравість для повідомлення перед авто",
				"zh-cn": "通知在尸体解出境之前的权利",
			},
			type: "number",
			role: "level.brightness",
			def: 10,
			min: 0,
			max: 100,
			unit: "%",
		},
		native: {},
	},
	"autoOffTimed.noticeEnabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Notice before auto off enabled?",
				de: "Hinweis vor Auto-aus aktiviert?",
				ru: "Уведомление, прежде чем активировать авто?",
				pt: "Notar antes de desligar automaticamente ativado?",
				nl: "Opmerking voor de auto in staat was?",
				fr: "Avis avant auto désactivé activé?",
				it: "Avviso prima di disattivare l'auto abilitato?",
				es: "¿Nota antes de activar el auto?",
				pl: "Przed wejściem do wersji auto zezwolono?",
				uk: "Повідомлення перед ввімкненням авто?",
				"zh-cn": "尸体解剖?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"autoOffTimed.noticeTime": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Time from notice to auto off",
				de: "Zeit ab Hinweis bis Auto-aus",
				ru: "Время от уведомления до авто",
				pt: "Tempo de aviso para auto off",
				nl: "Tijd van opmerking van de auto",
				fr: "Temps passé de l'avis à l'auto-arrêt",
				it: "Tempo di preavviso per disattivare",
				es: "Tiempo de aviso a auto apagado",
				pl: "Czas od czasu do czasu startu",
				uk: "Час від повідомлення до авто",
				"zh-cn": "退出通知的时间",
			},
			type: "number",
			role: "level.timer",
			def: 10,
			min: 0,
			unit: "s",
		},
		native: {},
	},
	autoOnLux: {
		type: "channel",
		common: {
			name: "autoOnLux",
		},
		native: {},
	},
	"autoOnLux.bri": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness of lights when auto on, if empty using groupstandard",
				de: "Helligkeit der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Яркость светов при авто на, если пуста с помощью группового стандарта",
				pt: "Brilho de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "Brightness of lights when auto on, als leeg met behulp van groepsstandard",
				fr: "Luminosité des lumières lorsqu'elles sont allumées, si elles sont vides en utilisant la norme de groupe",
				it: "Luminosità delle luci quando si accende, se vuoto utilizzando standard di gruppo",
				es: "Iluminación de luces cuando el auto encendido, si vacío usando groupstandard",
				pl: "Brightness of lights when auto, jeśli puste przy użyciu grupy standardowej",
				uk: "Яскравість вогнів при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "如果空洞使用零星的尸体解剖,那么照灯的完整性",
			},
			type: "number",
			role: "level.brightness",
			def: 0,
			min: 0,
			max: 100,
			unit: "%",
		},
		native: {},
	},
	"autoOnLux.color": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Color of lights when auto on, if empty using groupstandard",
				de: "Farbe der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Цвет света при авто на, если пустой с помощью группового стандарта",
				pt: "Cor de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "De kleur van de lichten als de auto aanstaat, als leeg met behulp van groepsgevangenis",
				fr: "Couleur des lumières lorsqu'elles sont allumées, si elles sont vides à l'aide de la norme de groupe",
				it: "Colore delle luci all'accensione automatica, se vuoto utilizzando standard di gruppo",
				es: "Color de luces cuando el auto encendido, si está vacío usando groupstandard",
				pl: "Kolor światła, gdy w samochodzie, jeśli puste przy użyciu grupy standardowej",
				uk: "Колір світильників при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "汽车时的照灯,如空用组空",
			},
			type: "string",
			role: "level.color.rgb",
			def: "#FFFFFF",
		},
		native: {},
	},
	"autoOnLux.dailyLock": {
		type: "state",
		common: {
			read: true,
			write: false,
			name: {
				en: "Switch lock",
				de: "Schaltsperre",
				ru: "Переключить замок",
				pt: "Bloqueio de interruptor",
				nl: "Vertaling:",
				fr: "Verrouillage",
				it: "Interruttore di blocco",
				es: "Cierre de interruptor",
				pl: "Switch",
				uk: "Блокування перемикача",
				"zh-cn": "黑暗锁",
			},
			type: "boolean",
			role: "indicator",
			def: false,
		},
		native: {},
	},
	"autoOnLux.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness controlled auto on enabled?",
				de: "Helligkeitgesteuertes Auto-ein aktiviert?",
				ru: "Яркость управляемая авто на включенном?",
				pt: "Controle de brilho automático ativado?",
				nl: "Brightness gecontroleerde auto op gehandicapten?",
				fr: "Auto contrôlée par luminosité activée ?",
				it: "Auto a controllo di luminosità attivata?",
				es: "¿Un auto controlado por Brightness?",
				pl: "Brightness sterował autom?",
				uk: "Яскравість керована автоматично на включенні?",
				"zh-cn": "自由控制的汽车吗?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"autoOnLux.minLux": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Necessary brightness for auto on",
				de: "Notwendige Helligkeit für Auto-ein",
				ru: "Необходимая яркость для авто на",
				pt: "Brilho necessário para automóvel em",
				nl: "Necessary slimheid voor auto",
				fr: "La luminosité nécessaire pour l'auto sur",
				it: "Luminosità necessaria per auto su",
				es: "El brillo necesario para el auto encendido",
				pl: "Niesamowite jasność dla auto",
				uk: "Необхідна яскравість для авто",
				"zh-cn": "汽车的必要光明",
			},
			type: "number",
			role: "level.brightness",
			def: 50,
			min: 0,
			unit: "lux",
		},
		native: {},
	},
	"autoOnLux.operator": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Should auto on happen if brightness more or less minLux",
				de: "Auto-ein wenn Helligkeit mehr oder weniger minLux",
				ru: "Должен ли автоматизироваться, если яркость больше или меньше minLux",
				pt: "Deve acontecer automaticamente se o brilho mais ou menos minLux",
				nl: "Er zou auto's moeten plaatsvinden als helderheid of minder",
				fr: "Si la luminosité est plus ou moins minLux",
				it: "Dovrebbe auto spento accadere se la luminosità più o meno minLux",
				es: "Si el auto apagado sucede si el brillo más o menos minLux",
				pl: "Auto zdejmuje się, jeśli jasność jest mniejsza niż minLux",
				uk: "Якщо яскравість більше або менше minLux",
				"zh-cn": "如果光明更小或小微不足道的光知会发生尸体解剖",
			},
			type: "string",
			role: "state",
			def: "<",
			states: {
				"<": "<",
				">": ">",
			},
		},
		native: {},
	},
	"autoOnLux.switchOnlyWhenNoPresence": {
		type: "state",
		common: {
			type: "boolean",
			read: true,
			write: true,
			name: {
				en: "Switch only if there is nobody at home?",
				de: "Nur Schalten, wenn niemand zu Hause ist?",
				ru: "Переключите только, если нет дома?",
				pt: "Mudar só se não houver ninguém em casa?",
				nl: "Alleen als er niemand thuis is?",
				fr: "Intervertir seulement s'il n'y a personne à la maison?",
				it: "Cambia solo se non c'è nessuno a casa?",
				es: "¿Cambiar sólo si no hay nadie en casa?",
				pl: "Switch tylko wtedy, gdy nikt nie żyje w domu?",
				uk: "Увімкніть тільки якщо немає нікого вдома?",
				"zh-cn": "只在家里没有人?",
			},
			role: "switch",
			def: false,
		},
		native: {},
	},
	"autoOnLux.switchOnlyWhenPresence": {
		type: "state",
		common: {
			type: "boolean",
			read: true,
			write: true,
			name: {
				en: "Switch only if there is somebody at home?",
				de: "Nur Schalten wenn jemand zu Hause ist?",
				ru: "Переключите только если кто-то дома?",
				pt: "Mudar só se houver alguém em casa?",
				nl: "Alleen als er iemand thuis is?",
				fr: "Si quelqu'un est à la maison ?",
				it: "Cambia solo se c'è qualcuno a casa?",
				es: "¿Cambiar sólo si hay alguien en casa?",
				pl: "Switch tylko wtedy, gdy jest ktoś w domu?",
				uk: "Увімкніть тільки, якщо є хтось вдома?",
				"zh-cn": "只在家里有一些人?",
			},
			role: "switch",
			def: true,
		},
		native: {},
	},
	autoOnMotion: {
		type: "channel",
		common: {
			name: "autoOnMotion",
		},
		native: {},
	},
	"autoOnMotion.bri": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness of lights when auto on, if empty using groupstandard",
				de: "Helligkeit der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Яркость светов при авто на, если пуста с помощью группового стандарта",
				pt: "Brilho de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "Brightness of lights when auto on, als leeg met behulp van groepsstandard",
				fr: "Luminosité des lumières lorsqu'elles sont allumées, si elles sont vides en utilisant la norme de groupe",
				it: "Luminosità delle luci quando si accende, se vuoto utilizzando standard di gruppo",
				es: "Iluminación de luces cuando el auto encendido, si vacío usando groupstandard",
				pl: "Brightness of lights when auto, jeśli puste przy użyciu grupy standardowej",
				uk: "Яскравість вогнів при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "如果空洞使用零星的尸体解剖,那么照灯的完整性",
			},
			type: "number",
			role: "level.brightness",
			def: 0,
			min: 0,
			max: 100,
			unit: "%",
		},
		native: {},
	},
	"autoOnMotion.color": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Color of lights when auto on, if empty using groupstandard",
				de: "Farbe der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Цвет света при авто на, если пустой с помощью группового стандарта",
				pt: "Cor de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "De kleur van de lichten als de auto aanstaat, als leeg met behulp van groepsgevangenis",
				fr: "Couleur des lumières lorsqu'elles sont allumées, si elles sont vides à l'aide de la norme de groupe",
				it: "Colore delle luci all'accensione automatica, se vuoto utilizzando standard di gruppo",
				es: "Color de luces cuando el auto encendido, si está vacío usando groupstandard",
				pl: "Kolor światła, gdy w samochodzie, jeśli puste przy użyciu grupy standardowej",
				uk: "Колір світильників при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "汽车时的照灯,如空用组空",
			},
			type: "string",
			role: "level.color.rgb",
			def: "#FFFFFF",
		},
		native: {},
	},
	"autoOnMotion.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Motion controlled auto on enabled?",
				de: "Bewegungsgesteuertes Auto-ein aktiviert?",
				ru: "Движение управляемое авто на включенном?",
				pt: "Movimento controlado automático ativado?",
				nl: "Motie gecontroleerde auto op gehandicapten?",
				fr: "Moteur de mouvement sur activé ?",
				it: "Moto controllata auto su abilitato?",
				es: "¿Motion control auto on enabled?",
				pl: "Kontrola auto na urządzeniach?",
				uk: "Ввімкнено автоматичне керування рухами?",
				"zh-cn": "摩擦控制的汽车?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"autoOnMotion.minLux": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Necessary brightness for auto on",
				de: "Notwendige Helligkeit für Auto-ein",
				ru: "Необходимая яркость для авто на",
				pt: "Brilho necessário para automóvel em",
				nl: "Necessary slimheid voor auto",
				fr: "La luminosité nécessaire pour l'auto sur",
				it: "Luminosità necessaria per auto su",
				es: "El brillo necesario para el auto encendido",
				pl: "Niesamowite jasność dla auto",
				uk: "Необхідна яскравість для авто",
				"zh-cn": "汽车的必要光明",
			},
			type: "number",
			role: "level.brightness",
			def: 300,
			min: 0,
			unit: "lux",
		},
		native: {},
	},
	autoOnPresenceIncrease: {
		type: "channel",
		common: {
			name: "autoOnPresenceIncrease",
		},
		native: {},
	},
	"autoOnPresenceIncrease.bri": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness of lights when auto on, if empty using groupstandard",
				de: "Helligkeit der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Яркость светов при авто на, если пуста с помощью группового стандарта",
				pt: "Brilho de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "Brightness of lights when auto on, als leeg met behulp van groepsstandard",
				fr: "Luminosité des lumières lorsqu'elles sont allumées, si elles sont vides en utilisant la norme de groupe",
				it: "Luminosità delle luci quando si accende, se vuoto utilizzando standard di gruppo",
				es: "Iluminación de luces cuando el auto encendido, si vacío usando groupstandard",
				pl: "Brightness of lights when auto, jeśli puste przy użyciu grupy standardowej",
				uk: "Яскравість вогнів при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "如果空洞使用零星的尸体解剖,那么照灯的完整性",
			},
			type: "number",
			role: "level.brightness",
			def: 0,
			max: 100,
			min: 0,
			unit: "%",
		},
		native: {},
	},
	"autoOnPresenceIncrease.color": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Color of lights when auto on, if empty using groupstandard",
				de: "Farbe der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Цвет света при авто на, если пустой с помощью группового стандарта",
				pt: "Cor de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "De kleur van de lichten als de auto aanstaat, als leeg met behulp van groepsgevangenis",
				fr: "Couleur des lumières lorsqu'elles sont allumées, si elles sont vides à l'aide de la norme de groupe",
				it: "Colore delle luci all'accensione automatica, se vuoto utilizzando standard di gruppo",
				es: "Color de luces cuando el auto encendido, si está vacío usando groupstandard",
				pl: "Kolor światła, gdy w samochodzie, jeśli puste przy użyciu grupy standardowej",
				uk: "Колір світильників при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "汽车时的照灯,如空用组空",
			},
			type: "string",
			role: "level.color.rgb",
			def: "#FFFFFF",
		},
		native: {},
	},
	"autoOnPresenceIncrease.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Presence controlled auto on enabled?",
				de: "Präsenzgesteuertes Auto-ein aktiviert?",
				ru: "Наличие контролируемого авто на включенном?",
				pt: "Presença controlada auto em ativado?",
				nl: "Druk gecontroleerde auto op in staat?",
				fr: "Auto contrôlée de présence sur activé ?",
				it: "Auto a controllo di presenza attivata?",
				es: "¿La presencia controlada en auto habilitado?",
				pl: "Przewiduje się, że auto jest kontrolowane?",
				uk: "Відстеження керованого авто на ввімкнено?",
				"zh-cn": "是否能够控制尸体?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"autoOnPresenceIncrease.minLux": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Necessary brightness for auto on",
				de: "Notwendige Helligkeit für Auto-ein",
				ru: "Необходимая яркость для авто на",
				pt: "Brilho necessário para automóvel em",
				nl: "Necessary slimheid voor auto",
				fr: "La luminosité nécessaire pour l'auto sur",
				it: "Luminosità necessaria per auto su",
				es: "El brillo necesario para el auto encendido",
				pl: "Niesamowite jasność dla auto",
				uk: "Необхідна яскравість для авто",
				"zh-cn": "汽车的必要光明",
			},
			type: "number",
			role: "level.brightness",
			def: 50,
			min: 0,
			unit: "lux",
		},
		native: {},
	},
	blink: {
		type: "channel",
		common: {
			name: "blink",
		},
		native: {},
	},
	"blink.blinks": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "How many blinks at activation?",
				de: "Wie viele Blinks bei der Aktivierung?",
				ru: "Сколько ссылок при активации?",
				pt: "Quantos piscas na ativação?",
				nl: "Hoeveel knipperen bij activatie?",
				fr: "Combien de liens à l'activation ?",
				it: "Quanti lampi all'attivazione?",
				es: "¿Cuántos parpadeos a la activación?",
				pl: "Jak wiele mrug w aktywacji?",
				uk: "Скільки посилань при активації?",
				"zh-cn": "如何启动多少环节?",
			},
			type: "number",
			role: "level",
			def: 3,
			min: 1,
		},
		native: {},
	},
	"blink.bri": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness of lights when auto on, if empty using groupstandard",
				de: "Helligkeit der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Яркость светов при авто на, если пуста с помощью группового стандарта",
				pt: "Brilho de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "Brightness of lights when auto on, als leeg met behulp van groepsstandard",
				fr: "Luminosité des lumières lorsqu'elles sont allumées, si elles sont vides en utilisant la norme de groupe",
				it: "Luminosità delle luci quando si accende, se vuoto utilizzando standard di gruppo",
				es: "Iluminación de luces cuando el auto encendido, si vacío usando groupstandard",
				pl: "Brightness of lights when auto, jeśli puste przy użyciu grupy standardowej",
				uk: "Яскравість вогнів при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "如果空洞使用零星的尸体解剖,那么照灯的完整性",
			},
			type: "number",
			role: "level.brightness",
			def: 100,
			max: 100,
			min: 0,
			unit: "%",
		},
		native: {},
	},
	"blink.color": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Color of lights when auto on, if empty using groupstandard",
				de: "Farbe der Lampen bei Auto-ein, wenn leer mit Gruppenstandard",
				ru: "Цвет света при авто на, если пустой с помощью группового стандарта",
				pt: "Cor de luzes quando ligado automaticamente, se vazio usando padrão de grupo",
				nl: "De kleur van de lichten als de auto aanstaat, als leeg met behulp van groepsgevangenis",
				fr: "Couleur des lumières lorsqu'elles sont allumées, si elles sont vides à l'aide de la norme de groupe",
				it: "Colore delle luci all'accensione automatica, se vuoto utilizzando standard di gruppo",
				es: "Color de luces cuando el auto encendido, si está vacío usando groupstandard",
				pl: "Kolor światła, gdy w samochodzie, jeśli puste przy użyciu grupy standardowej",
				uk: "Колір світильників при автоматичному режимі, якщо порожній за допомогою груповогостандарту",
				"zh-cn": "汽车时的照灯,如空用组空",
			},
			type: "string",
			role: "level.color.rgb",
			def: "#FF0000",
		},
		native: {},
	},
	"blink.enabled": {
		type: "state",
		common: {
			type: "boolean",
			read: true,
			write: true,
			name: {
				en: "Blinking enabled?",
				de: "Blinken aktiviert?",
				ru: "Blinking включен?",
				pt: "Blinking ativado?",
				nl: "In staat knipperen?",
				fr: "Clignote activée ?",
				it: "Collegamento abilitato?",
				es: "¿Blinking habilitado?",
				pl: "Umożliwia to Blinking?",
				uk: "Увімкнути посилання?",
				"zh-cn": "联系是否能够?",
			},
			role: "switch",
			def: false,
		},
		native: {},
	},
	"blink.frequency": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Blink frequency in seconds",
				de: "Blink-Frequenz in Sekunden",
				ru: "Частота Blink в секундах",
				pt: "Frequência de ligação em segundos",
				nl: "Blink frequentie in seconden",
				fr: "Fréquence de connexion en secondes",
				it: "Frequenza di collegamento in secondi",
				es: "Frecuencia de enlace en segundos",
				pl: "Częstotliwość Blinka w sekundach",
				uk: "Частота Blink в секундах",
				"zh-cn": "二、二者之间的联系频率",
			},
			type: "number",
			role: "level",
			def: 1,
			min: 1,
			unit: "s",
		},
		native: {},
	},
	"blink.start": {
		type: "state",
		common: {
			read: false,
			write: true,
			name: {
				en: "Start Blinking until number of blinks",
				de: "Blinken starten bis zur Anzahl der Blinks",
				ru: "Начните Blinking до количества blinks",
				pt: "Comece a piscar até o número de links",
				nl: "Begin met knipperen tot het aantal knipperlichten",
				fr: "Commencer à clignoter jusqu'au nombre de clignotes",
				it: "Inizia a lampeggiare fino al numero di lampioni",
				es: "Empieza a parpadear hasta el número de parpadeos",
				pl: "Start Blinking until the number of blinks (ang.)",
				uk: "Почати посилання до кількості посилань",
				"zh-cn": "B. 连接到链接次数",
			},
			type: "boolean",
			role: "button.start",
			def: false,
		},
		native: {},
	},
	bri: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightness",
				de: "Helligkeit",
				ru: "Яркость",
				pt: "Brilho",
				nl: "Brightness",
				fr: "Luminosité",
				it: "Luminosità",
				es: "Brillo",
				pl: "Brightness",
				uk: "Яскравість",
				"zh-cn": "B. 权利",
			},
			type: "number",
			role: "level.brightness",
			def: 100,
			min: 0,
			max: 100,
			unit: "%",
		},
		native: {},
	},
	color: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Color",
				de: "Farbe",
				ru: "Цвет",
				pt: "Cor",
				nl: "Color",
				fr: "Couleur",
				it: "Colore",
				es: "Color",
				pl: "Color",
				uk: "Колір",
				"zh-cn": "科 法 律",
			},
			type: "string",
			role: "level.color.rgb",
			def: "#FFFFFF",
		},
		native: {},
	},
	ct: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Colortemperature",
				de: "Farbtemperatur",
				ru: "Цветная температура",
				pt: "Temperatura de cor",
				nl: "Colortemperatuur",
				fr: "Colortemperature",
				it: "Coloratemperature",
				es: "Colortemperatura",
				pl: "Colortemperatura",
				uk: "Кольори",
				"zh-cn": "法定人数",
			},
			type: "number",
			role: "level.color.temperature",
			def: 3300,
			min: 0,
			max: 10000,
			unit: "K",
		},
		native: {},
	},
	dimmAmount: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Brightnesssteps for dimming",
				de: "Helligkeitsstufen zum Dimmen",
				ru: "Яркие шаги для затемнения",
				pt: "Brilho passos para escurecimento",
				nl: "Brightnesssteps voor dimmen",
				fr: "Étapes de luminosité pour le dimming",
				it: "Passi di luminosità per dimming",
				es: "Brightnesssteps for dimming",
				pl: "Brightnessstep for dimming (ang.)",
				uk: "Яскравістьпокроків для занурення",
				"zh-cn": "B. 降 权",
			},
			type: "number",
			role: "level.brightness",
			def: 10,
			min: 2,
			max: 50,
			unit: "%",
		},
		native: {},
	},
	dimmDown: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Dimm Down",
				de: "Runterdimmen",
				ru: "Димм вниз",
				pt: "Dimm para baixo",
				nl: "Dimm Down",
				fr: "Dimm Down",
				it: "Dimm giù",
				es: "Dimm Down",
				pl: "Dimm Down (ang.)",
				uk: "Dimm вниз",
				"zh-cn": "D. 甲烷",
			},
			type: "boolean",
			role: "button",
			def: false,
		},
		native: {},
	},
	dimmUp: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Dimm Up",
				de: "Hochdimmen",
				ru: "Димм Up",
				pt: "Dimm Up",
				nl: "Dimm Up",
				fr: "Dimm Up",
				it: "Dimm su",
				es: "Dimm Up",
				pl: "Dimm Up (ang.)",
				uk: "Dimm Вгору",
				"zh-cn": "迪米",
			},
			type: "boolean",
			role: "button",
			def: false,
		},
		native: {},
	},
	isMotion: {
		type: "state",
		common: {
			read: true,
			write: false,
			name: {
				en: "Combines the states of all sensors for this group",
				de: "Kombiniert die Zustände aller Sensoren für diese Gruppe",
				ru: "Сочетает состояния всех датчиков для этой группы",
				pt: "Combina os estados de todos os sensores para este grupo",
				nl: "Combineert de staat van alle sensoren voor deze groep",
				fr: "Combine les états de tous les capteurs pour ce groupe",
				it: "Combina gli stati di tutti i sensori per questo gruppo",
				es: "Combina los estados de todos los sensores para este grupo",
				pl: "Kombinuje stany wszystkich czujników tej grupy",
				uk: "Комбінує стани всіх датчиків для цієї групи",
				"zh-cn": "本组的所有传感站",
			},
			type: "boolean",
			role: "indicator.motion",
			def: false,
		},
		native: {},
	},
	power: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: "Power",
			type: "boolean",
			role: "switch.power",
			def: false,
		},
		native: {},
	},
	powerCleaningLight: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: "Power cleaning light",
			type: "boolean",
			role: "switch.power",
			def: false,
		},
		native: {},
	},
	rampOff: {
		type: "channel",
		common: {
			name: "rampOff",
		},
		native: {},
	},
	"rampOff.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Ramping off enabled?",
				de: "Runterrampen aktiviert?",
				ru: "Рампинг включен?",
				pt: "Desligar activado?",
				nl: "Ingewikkeld?",
				fr: "L'enlèvement est activé ?",
				it: "Rimozione attivata?",
				es: "¿Se ha activado?",
				pl: "Umożliwiło to zezwolenie?",
				uk: "Вимкнено рух?",
				"zh-cn": "离开?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"rampOff.switchOutletsLast": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Switch outlets after ramping?",
				de: "Lampen welche nur ein-/ausgeschaltet werden zuletzt deaktivieren?",
				ru: "Переключение точек после ramping?",
				pt: "Trocar tomadas depois de bater?",
				nl: "Verwijderingen na de oprit?",
				fr: "Interrupteurs après avoir rampé ?",
				it: "Accendere le prese dopo la rampa?",
				es: "¿Cambiar las salidas después de la rampa?",
				pl: "Switch wybiega po wyburzeniu?",
				uk: "Вимкніть розетки після обрамлення?",
				"zh-cn": "之后的传单?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"rampOff.time": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Time in seconds for ramping off duration",
				de: "Zeit in Sekunden für das Runterrampen",
				ru: "Время в считанные секунды для ramping off продолжительность",
				pt: "Tempo em segundos para arrancar a duração",
				nl: "Tijd in een seconde voor het vervoeren van",
				fr: "Temps en quelques secondes pour l'arrêt",
				it: "Tempo in secondi per dilagare la durata",
				es: "Tiempo en segundos para despegar la duración",
				pl: "Czas na sekundę za przechylenie czasu",
				uk: "Час в секундах для обрамлення тривалістю",
				"zh-cn": "二. 时间",
			},
			type: "number",
			role: "level",
			def: 10,
			min: 0,
			unit: "s",
		},
		native: {},
	},
	rampOn: {
		type: "channel",
		common: {
			name: "rampOn",
		},
		native: {},
	},
	"rampOn.enabled": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Ramping on enabled?",
				de: "Hochrampen aktiviert?",
				ru: "Рампинг на включенном?",
				pt: "A entrar activado?",
				nl: "Ingewikkeld?",
				fr: "On s'y met ?",
				it: "Ramping attivato?",
				es: "¿Golpeando?",
				pl: "Umożliwiło to umożliwienie?",
				uk: "Рампінг на ввімкнено?",
				"zh-cn": "是否允许?",
			},
			type: "boolean",
			role: "switch.enable",
			def: false,
		},
		native: {},
	},
	"rampOn.switchOutletsLast": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Switch outlets after ramping?",
				de: "Lampen welche nur ein-/ausgeschaltet werden zuletzt aktivieren?",
				ru: "Переключение точек после ramping?",
				pt: "Trocar tomadas depois de bater?",
				nl: "Verwijderingen na de oprit?",
				fr: "Interrupteurs après avoir rampé ?",
				it: "Accendere le prese dopo la rampa?",
				es: "¿Cambiar las salidas después de la rampa?",
				pl: "Switch wybiega po wyburzeniu?",
				uk: "Вимкніть розетки після обрамлення?",
				"zh-cn": "之后的传单?",
			},
			type: "boolean",
			role: "switch.enable",
			def: true,
		},
		native: {},
	},
	"rampOn.time": {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Time in seconds for ramping on duration",
				de: "Zeit in Sekunden für Hochrampen",
				ru: "Время в секундах для ramping на длительность",
				pt: "Tempo em segundos para tocar na duração",
				nl: "Tijd in een seconde voor het vervoeren van",
				fr: "Temps en secondes pour ramper sur la durée",
				it: "Tempo in secondi per dilagare sulla durata",
				es: "Tiempo en segundos para aumentar la duración",
				pl: "Czas w sekundach na pogorszenie się czasu",
				uk: "Час в секундах для обрамлення на тривалість",
				"zh-cn": "二. 时间间隔",
			},
			type: "number",
			role: "level",
			def: 10,
			min: 0,
			unit: "s",
		},
		native: {},
	},
	transitionTime: {
		type: "state",
		common: {
			read: true,
			write: true,
			name: {
				en: "Regular Transition Time",
				de: "Reguläre Übergangszeit",
				ru: "Регулярное время перехода",
				pt: "Tempo de transição regular",
				nl: "Regular Transition Time",
				fr: "Temps de transition régulier",
				it: "Tempo di transizione regolare",
				es: "Tiempo de transición regular",
				pl: "Czas regularny",
				uk: "Регулярний час переходу",
				"zh-cn": "定期过渡",
			},
			type: "number",
			role: "state",
			def: 1000,
			unit: "ms",
		},
		native: {},
	},
};
