const TestTemplateLamps = {
	Lamp1: {
		power : {
			read: true,
			write: true,
			name: "Power",
			type: "boolean",
			role: "switch.power",
			def: false,
		},
		bri: {
			read: true,
			write: true,
			name: "Brightness",
			type: "number",
			role: "level.brightness",
			def: 100,
			min: 0,
			max: 100,
			unit: "%",
		},
		sat: {
			read: true,
			write: true,
			name: "Saturation",
			type: "number",
			role: "level.sat",
			def: 0,
			min: 0,
			max: 100,
		},
		ct: {
			read: true,
			write: true,
			name: "Colortemperature",
			type: "number",
			role: "level.color.temperature",
			def: 300,
		},
		colorHEX: {
			read: true,
			write: true,
			name: "Color Hex",
			type: "string",
			role: "level.color.rgb",
			def: "#FFFFFF",
		},
		colorModeSwitch: {
			read: true,
			write: true,
			name: "Color ModeSwitch",
			type: "boolean",
			role: "value",
			def: "false",
		},
	},
	Lamp2: {
		power : {
			read: true,
			write: true,
			name: "Power",
			type: "boolean",
			role: "switch.power",
			def: false,
		},
		bri: {
			read: true,
			write: true,
			name: "Brightness",
			type: "number",
			role: "level.brightness",
			def: 100,
			min: 0,
			max: 100,
			unit: "%",
		},
		sat: {
			read: true,
			write: true,
			name: "Saturation",
			type: "number",
			role: "level.sat",
			def: 0,
			min: 0,
			max: 100,
		},
		ct: {
			read: true,
			write: true,
			name: "Colortemperature",
			type: "number",
			role: "level.color.temperature",
			def: 300,
			unit: "K",
		},
		colorRGB: {
			read: true,
			write: true,
			name: "Color RGB",
			type: "number",
			role: "level.color.RGB",
			def: 250,
		},
		colorModeSwitch: {
			read: true,
			write: true,
			name: "Color ModeSwitch",
			type: "boolean",
			role: "value",
			def: "false",
		},
	},
	Lamp3: {
		power : {
			read: true,
			write: true,
			name: "Power",
			type: "boolean",
			role: "switch.power",
			def: false,
		},
		bri: {
			read: true,
			write: true,
			name: "Brightness",
			type: "number",
			role: "level.brightness",
			def: 100,
			min: 0,
			max: 100,
			unit: "%",
		},
		sat: {
			read: true,
			write: true,
			name: "Saturation",
			type: "number",
			role: "level.sat",
			def: 0,
			min: 0,
			max: 100,
		},
		ct: {
			read: true,
			write: true,
			name: "Colortemperature",
			type: "number",
			role: "level.color.temperature",
			def: 300,
			unit: "K",
		},
		colorXY: {
			read: true,
			write: true,
			name: "Color XY",
			type: "string",
			role: "level.color.xy",
			def: "[0.4992,0.418]",
		},
		colorModeSwitch: {
			read: true,
			write: true,
			name: "Color ModeSwitch",
			type: "boolean",
			role: "value",
			def: "false",
		},
	},
};

const TestTemplateMotionSensors = {
	MotionSensor1 : {
		read: true,
		write: true,
		name: "Motion Sensor 1",
		type: "boolean",
		role: "sensor.motion",
		def: false,
	},
	MotionSensor2 : {
		read: true,
		write: true,
		name: "Motion Sensor 2",
		type: "boolean",
		role: "sensor.motion",
		def: false,
	},
	MotionSensor3 : {
		read: true,
		write: true,
		name: "Motion Sensor 3",
		type: "boolean",
		role: "sensor.motion",
		def: false,
	},
};

const TestTemplateLuxSensors = {
	LuxSensor1 : {
		read: true,
		write: true,
		name: "Lux Sensor 1",
		type: "number",
		role: "value.brightness",
		def: 50,
	},
	LuxSensor2 : {
		read: true,
		write: true,
		name: "Lux Sensor 2",
		type: "number",
		role: "value.brightness",
		def: 50,
	},
	GlobalLuxSensor : {
		read: true,
		write: true,
		name: "Lux Sensor 3",
		type: "number",
		role: "value.brightness",
		def: 50,
	},
};

const TestTemplatePresence = {
	PresenceCountDp : {
		read: true,
		write: true,
		name: "Presence Counter",
		type: "number",
		role: "value",
		def: 0,
	},
	IsPresenceDp : {
		read: true,
		write: true,
		name: "IsPresenceDp",
		type: "boolean",
		role: "state",
		def: true,
	},
};

module.exports = {
	TestTemplateLamps,
	TestTemplateMotionSensors,
	TestTemplateLuxSensors,
	TestTemplatePresence,
};
